version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: taskmanagement
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  app:
    image: tms-image
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
